name: Create Staging

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  # only these listed tables will be copied over to the staging environment
  TABLES: '["pgbench_accounts", "pgbench_branches", "pgbench_history", "pgbench_tellers"]'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install PostgreSQL 16
        run: |
          sudo apt install -y postgresql-common
          yes '' | sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh
          sudo apt-get install -y postgresql-client-16
          echo "/usr/lib/postgresql/16/bin" >> $GITHUB_PATH

      - name: Pipe
        run: |
          pg_dump -Fc -v -t ${{ join(fromJSON(env.TABLES), ' -t ') }} -d ${{ secrets.PRODUCTION_DATABASE_URL }} | pg_restore -v -C --no-owner --no-acl --clean --if-exists -d ${{ secrets.STAGING_DATABASE_URL }}
